---
- name: Deploy Fruit Backend
  hosts: fruitbackend
  collections:
    - nginxinc.nginx_core
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-11-jdk
      become: yes
  vars:
    environment_file: "/etc/fruit/environment"
  tasks:
    - name: Update apt-get repo and cache & Upgrade
      apt: update_cache=yes upgrade=dist force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: Install Python lxml
      become: yes
      apt:
        name: python3-lxml

    - name: Add the springboot user
      become: yes
      ansible.builtin.user:
        name: springboot
        comment: Spring Boot
        shell: /sbin/nologin
        create_home: no

    - name: Make App Dirs
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        owner: springboot
        group: springboot
        mode: 0775
      loop:
        - /app/a
        - /app/b

    - name: Download fruit app JAR
      no_log: true
      become: yes
      community.general.maven_artifact:
        group_id: com.bites
        artifact_id: fruit
        version: latest
        verify_checksum: always
        repository_url: 'https://maven.pkg.github.com/shuaiscott/Bites'
        username: _
        password: '{{ github_maven_pat }}'
        dest: /app/{{ item.slot }}/fruit.jar
        owner: springboot
        group: springboot
        mode: 0744
      loop:
        - { slot: 'a' }
        - { slot: 'b' }

    # Install Systemd services
    - name: Make Systemd environment directory
      become: yes
      file:
        path: "/etc/fruit/"
        state: directory
        owner: springboot
        group: springboot
        mode: 0700
    
    - name: Install Systemd Environment file
      become: yes
      template:
        src: templates/fruit/systemd-environment.j2
        dest: '{{ environment_file }}.{{ item.slot }}'
        owner: springboot
        group: springboot
        mode: 0700
      vars:
        app_port: "{{ item.app_port }}"
      loop:
        - { slot: 'a', app_port: 8081 }
        - { slot: 'b', app_port: 8082 }

    - name: Install Slot(s) Systemd
      become: yes
      template:
        src: templates/fruit/systemd.service.j2
        dest: "/etc/systemd/system/fruit-{{ item.slot }}.service"
        owner: root
        group: root
        mode: 0644
      vars:
        service_exec: "/app/{{ item.slot }}/fruit.jar"
        service_description: "Fruit Service Slot {{ item.slot | capitalize }}"
        service_user: springboot
        service_env_file: '{{ environment_file }}.{{ item.slot }}'
      loop:
        - { slot: 'a' }
        - { slot: 'b' }

    - name: Enable fruit service systemd
      become: yes
      ansible.builtin.systemd:
        name: fruit-{{ item.slot }}.service
        state: started
        enabled: yes
        daemon_reload: yes
      loop:
        - { slot: 'a' }
        - { slot: 'b' }